SERVER:
  USER: "test"
  PASS: "test"
  AUTH_ENABLED: false
  PORT: 8082
LOGGER:
  LOGLEVEL: TRACE
  GRAYLOG_ACTIVE: false
  GRAYLOG_SERVER: "localhost"
  GRAYLOG_STREAM: "FXPROXY"
  DISABLE_STDOUT: false
PROXY:
  DEFAULT_TTL: 43200
